version: 2

sources:
  - name: raw_banking
    database: BANKING_DB
    schema: AIRFLOW_RAW
    tables:
      - name: RAW_CARDS
        columns:
          - name: CARD_ID
            tests:
              - not_null
              - unique
      - name: RAW_CUSTOMERS
        columns:
          - name: CUSTOMER_ID
            tests:
              - not_null
              - unique
      - name: RAW_MERCHANTS
        columns:
          - name: MERCHANT_ID
            tests:
              - not_null
              - unique
      - name: RAW_TRANSACTIONS
        columns:
          - name: TRANSACTION_ID
            tests:
              - not_null
              - unique
